services:
  postgres-test:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./integration/testdata:/docker-entrypoint-initdb.d